GET http://localhost:3003/api/cards/67bfe0eccffd270dfe8e3f19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhvbHlydXMiLCJpZCI6IjY3YmZkNzEzZTA4NTVjNGYwMDgzODBiOSIsImlhdCI6MTc0MDc5NTkxMywiZXhwIjoxNzQwNzk5NTEzfQ.wuW8Faq3JgFNIO3zDn4JQW9oZoI_Ur6dE-_uD93DMr8

###

POST http://localhost:3003/api/cards/67bfe110cffd270dfe8e3f29
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhvbHlydXMiLCJpZCI6IjY3YmZkNzEzZTA4NTVjNGYwMDgzODBiOSIsImlhdCI6MTc0MDc5NTkxMywiZXhwIjoxNzQwNzk5NTEzfQ.wuW8Faq3JgFNIO3zDn4JQW9oZoI_Ur6dE-_uD93DMr8

{
  "word": "Dog",
  "translation": "Собака",
  "usage": "This is my dog, Rex"
}

###

DELETE http://localhost:3003/api/cards/67c273b3e4c31d2d6aa33db0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhvbHlydXMiLCJpZCI6IjY3YmZkNzEzZTA4NTVjNGYwMDgzODBiOSIsImlhdCI6MTc0MDc5NTkxMywiZXhwIjoxNzQwNzk5NTEzfQ.wuW8Faq3JgFNIO3zDn4JQW9oZoI_Ur6dE-_uD93DMr8

###

PUT http://localhost:3003/api/cards/67c273b3e4c31d2d6aa33db0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhvbHlydXMiLCJpZCI6IjY3YmZkNzEzZTA4NTVjNGYwMDgzODBiOSIsImlhdCI6MTc0MDc5NTkxMywiZXhwIjoxNzQwNzk5NTEzfQ.wuW8Faq3JgFNIO3zDn4JQW9oZoI_Ur6dE-_uD93DMr8

{
  "word": "Doggy",
  "translation": "Собака",
  "usage": "This is my doggy, Rex"
}

###